version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chatbot-db
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot1994
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot -d chatbotdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatbotdb
      SPRING_DATASOURCE_USERNAME: *******
      SPRING_DATASOURCE_PASSWORD:  *******
      SPRING_DATASOURCE_DRIVER_CLASS_NAME:  *******
      SPRING_APPLICATION_NAME:  *******
      API_SECURITY_TOKEN_SECRET:  *******
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALEC: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - chatbot-network
  whatsapp-node:
    build:
      context: ../../agentNode
      dockerfile: Dockerfile
    container_name: whatsapp-node
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: *******
      DB_PASSWORD:  *******
      DB_NAME:  *******
    ports:
      - "3000:3000"
    networks:
      - chatbot-network

volumes:
  postgres_data:

networks:
  chatbot-network:
